name: Update Server

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/skipper_backend:latest
      - name: Update project on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/buroroll/skipper_backend/backend
            docker stop skipper_backend
            docker rm skipper_backend
            docker rmi --force buroroll/skipper_backend
            docker run -d -p 8000:8000 --env-file .env --name skipper_backend -v /home/buroroll/skipper_backend/backend/static_files:/app/media/user/profile_picture/ --restart unless-stopped buroroll/skipper_backend:latest
